// <auto-generated />
namespace demo_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class second2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(second2));
        
        string IMigrationMetadata.Id
        {
            get { return "201912301148192_second2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
