// <auto-generated />
namespace demo_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class second5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(second5));
        
        string IMigrationMetadata.Id
        {
            get { return "202001011058249_second5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
